### ISSUE TITLE
the groundtruth format in txt for bdd100k is wrong for darknet

### ISSUE THREAD

**Issue by xiuyangleiasp** [sanwong15/yolo-v3-with-bdd#3]
according codes: https://github.com/sanwong15/yolo-v3-with-bdd/blob/81cceae7321f0f4ea55278aea964c72285911078/codes/bdd100k/extract_labels.py#L93
your format is "cls_id x y h w",
but the format in darknet is "cls_id x y w h".

**Comment by priteshgohil** [comment]
I have observed the same @xiuyangleiasp . 
Author should change it
